// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Raffle.Api.Database;

#nullable disable

namespace Raffle.Api.Migrations
{
    [DbContext(typeof(RaffleDbContext))]
    partial class RaffleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Raffle.Api.Models.RaffleDraw", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WinnerMemberId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("WinnerMemberId");

                    b.ToTable("RaffleDraws");
                });

            modelBuilder.Entity("Raffle.Api.Models.RaffleMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RaffleDrawId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RaffleDrawId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Raffle.Api.Models.RaffleDraw", b =>
                {
                    b.HasOne("Raffle.Api.Models.RaffleMember", "WinnerMember")
                        .WithMany()
                        .HasForeignKey("WinnerMemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("WinnerMember");
                });

            modelBuilder.Entity("Raffle.Api.Models.RaffleMember", b =>
                {
                    b.HasOne("Raffle.Api.Models.RaffleDraw", "RaffleDraw")
                        .WithMany("RaffleMembers")
                        .HasForeignKey("RaffleDrawId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RaffleDraw");
                });

            modelBuilder.Entity("Raffle.Api.Models.RaffleDraw", b =>
                {
                    b.Navigation("RaffleMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
